use std::collections::BTreeSet;
use std::fs;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt as _;
use std::path::Path;
use std::process::Command;

use swc_core::ecma::ast::{Decl, Module, ModuleDecl, ModuleItem, Pat};

use super::swc_generation::{
    emit_declarations, parse_es_module_for_test, parse_ts_module_for_test,
};
use super::{
    ApiVersion, BuildProvenance, GenerationMetadata, VersionLedger, canonical_source_hash,
    generate_artifacts, read_ledger,
};

const REQUIRED_RUNTIME_EXPORTS: [&str; 16] = [
    "API_REVISION",
    "API_VERSION",
    "AllocationProposal",
    "ArchiveDownload",
    "ContentFormat",
    "ContentFormats",
    "BUILD_COMMIT",
    "BUILD_DIRTY",
    "GENERATOR_VERSION",
    "MediaType",
    "MediaTypes",
    "Operation",
    "SOURCE_HASH",
    "SymbolApiError",
    "SymbolClient",
    "metadata",
];

#[derive(Debug, PartialEq, Eq)]
struct HeaderIdentity {
    api_version: String,
    absolute_revision: String,
    source_hash: String,
    generator_version: String,
    commit: String,
    state: String,
}

#[test]
fn generated_metadata_and_artifact_headers_are_identical() {
    let root = workspace_root();
    let metadata = test_metadata(&root);
    let artifacts = generate_artifacts(&root, &metadata).unwrap();
    let sources = [
        ("//", "symbol.ts", &artifacts.api_ts),
        ("//", "symbol.js", &artifacts.api_js),
        ("//", "symbol.global.js", &artifacts.api_global_js),
        ("//", "symbol.d.ts", &artifacts.api_d_ts),
        ("#", "symbol.py", &artifacts.api_py),
    ];
    let expected_identity = header_identity(&artifacts.api_ts);
    for (comment, artifact, source) in sources {
        assert!(
            source.starts_with(&format!(
                "{comment} @generated by symbol-generation; DO NOT EDIT.\n"
            )),
            "{artifact}"
        );
        assert!(
            source.contains(&format!("{comment} Artifact: {artifact}\n")),
            "{artifact}"
        );
        assert_eq!(header_identity(source), expected_identity, "{artifact}");
    }

    assert!(
        artifacts
            .api_ts
            .contains("\\\"artifact\\\":\\\"symbol.ts\\\"")
    );
    assert!(
        artifacts
            .api_js
            .contains("\\\"artifact\\\":\\\"symbol.js\\\"")
    );
    assert!(
        artifacts
            .api_global_js
            .contains("\\\"artifact\\\":\\\"symbol.global.js\\\"")
    );
    assert!(artifacts.api_py.contains("\"artifact\":\"symbol.py\""));
}

#[test]
fn complete_generation_is_byte_identical_on_repeat() {
    let root = workspace_root();
    let metadata = test_metadata(&root);
    let first = generate_artifacts(&root, &metadata).unwrap();
    let second = generate_artifacts(&root, &metadata).unwrap();
    assert_eq!(first, second);

    let api_source = fs::read_to_string(root.join("API.md")).unwrap();
    let first_manuals = super::docs::compile(&api_source).unwrap();
    let second_manuals = super::docs::compile(&api_source).unwrap();
    assert_eq!(first_manuals, second_manuals);
}

#[test]
fn swc_outputs_have_runtime_export_parity_and_declarations_only() {
    let root = workspace_root();
    let artifacts = generate_artifacts(&root, &test_metadata(&root)).unwrap();

    let typescript = parse_ts_module_for_test(&artifacts.api_ts).unwrap();
    let javascript = parse_es_module_for_test(&artifacts.api_js).unwrap();
    let declarations = parse_ts_module_for_test(&artifacts.api_d_ts).unwrap();
    parse_es_module_for_test(&artifacts.api_global_js).unwrap();

    let expected = runtime_exports(&typescript);
    assert_eq!(runtime_exports(&javascript), expected);
    assert_eq!(runtime_exports(&declarations), expected);
    for required in REQUIRED_RUNTIME_EXPORTS {
        assert!(expected.contains(required), "{required}");
        assert!(
            artifacts
                .api_global_js
                .contains(&format!("get {required} ()")),
            "UMD omitted {required}"
        );
    }
    assert!(!artifacts.api_js.contains("interface SymbolApiMetadata"));
    assert!(!artifacts.api_global_js.contains("export "));
    assert!(artifacts.api_global_js.contains(".SymbolAPI"));

    for item in &declarations.body {
        let ModuleItem::ModuleDecl(ModuleDecl::ExportDecl(export)) = item else {
            continue;
        };
        let Decl::Var(variable) = &export.decl else {
            continue;
        };
        assert!(variable.declare);
        assert!(
            variable
                .decls
                .iter()
                .all(|declarator| declarator.init.is_none())
        );
    }
}

#[test]
fn declarations_cover_exported_types_functions_and_classes() {
    let source = r#"
const hidden = 1;
function helper(): number { return hidden; }
export interface RequestOptions { timeoutMs?: number; }
export type Result<T> = { value: T };
export function request(path: string, options?: RequestOptions): Promise<Result<string>> {
    return Promise.resolve({ value: path });
}
export class Client {
    #secret = 1;
    private token: string = "secret";
    readonly endpoint: string = "https://example.invalid";
    constructor(endpoint: string) { this.endpoint = endpoint; }
    request(path: string): Promise<string> { return Promise.resolve(path); }
    private reset(): void { this.token = ""; }
}
export const DEFAULT_TIMEOUT: number = 30;
"#;
    let declarations = emit_declarations(source, "golden.ts").unwrap();
    let expected = r#"export interface RequestOptions {
    timeoutMs?: number;
}
export type Result<T> = {
    value: T;
};
export declare function request(path: string, options?: RequestOptions): Promise<Result<string>>;
export declare class Client {
    readonly endpoint: string;
    constructor(endpoint: string);
    request(path: string): Promise<string>;
}
export declare const DEFAULT_TIMEOUT: number;
"#;
    assert_eq!(declarations, expected);
    parse_ts_module_for_test(&declarations).unwrap();
    for forbidden in [
        "hidden",
        "helper",
        "#secret",
        "token",
        "reset",
        "Promise.resolve",
        "\"secret\"",
        "\"https://example.invalid\"",
    ] {
        assert!(!declarations.contains(forbidden), "{forbidden}");
    }
}

#[test]
fn declarations_retain_private_type_dependencies_and_strip_namespaces_recursively() {
    let source = r#"
interface WireValue { value: string; }
type WireResult = { result: WireValue };
const runtimeHelper = 1;
export function decode(value: WireValue): WireResult {
    return { result: value };
}
export namespace SDK {
    interface Request { path: string; }
    export function request(input: Request): Promise<Request> {
        return Promise.resolve(input);
    }
    export class Client {
        private token: string = "secret";
        request(input: Request): Promise<Request> { return Promise.resolve(input); }
        private reset(): void { this.token = ""; }
    }
    export namespace Nested {
        export function create(input: Request): Request { return input; }
    }
}
"#;
    let declarations = emit_declarations(source, "namespace-golden.ts").unwrap();
    let expected = r#"interface WireValue {
    value: string;
}
type WireResult = {
    result: WireValue;
};
export declare function decode(value: WireValue): WireResult;
export declare namespace SDK {
    interface Request {
        path: string;
    }
    export function request(input: Request): Promise<Request>;
    export class Client {
        request(input: Request): Promise<Request>;
    }
    export namespace Nested {
        export function create(input: Request): Request;
    }
}
"#;
    assert_eq!(declarations, expected);
    parse_ts_module_for_test(&declarations).unwrap();
    assert!(!declarations.contains("runtimeHelper"));
    for forbidden in ["Promise.resolve", "\"secret\"", "token", "reset", "return "] {
        assert!(!declarations.contains(forbidden), "{forbidden}");
    }
    typecheck_declarations_if_available(&declarations);
}

#[test]
fn declarations_strip_defaults_async_and_overload_implementations() {
    let source = r#"
export async function load(limit: number = 10): Promise<number> {
    return limit;
}
export class Client {
    constructor(endpoint: string = "https://example.invalid") {}
    files(): Promise<string>;
    files(path: string): Promise<number>;
    async files(pathOrNothing: string | undefined = undefined): Promise<string | number> {
        return pathOrNothing ?? "";
    }
    async close(reason: string = "done"): Promise<void> {}
}
"#;
    let declarations = emit_declarations(source, "defaults-golden.ts").unwrap();
    let expected = r#"export declare function load(limit?: number): Promise<number>;
export declare class Client {
    constructor(endpoint?: string);
    files(): Promise<string>;
    files(path: string): Promise<number>;
    close(reason?: string): Promise<void>;
}
"#;
    assert_eq!(declarations, expected);
    parse_ts_module_for_test(&declarations).unwrap();
    typecheck_declarations_if_available(&declarations);
}

#[test]
fn declarations_hide_operation_construction_and_internal_support_types() {
    let source = r#"
interface InternalOperationConfiguration {
    retry: boolean;
}
type InternalAttemptExecutor<T> = () => Promise<T>;
export class Operation<T> {
    constructor(
        configuration: InternalOperationConfiguration,
        executor: InternalAttemptExecutor<T>,
    ) {}
    value(): T { throw new Error("runtime only"); }
}
"#;
    let declarations = emit_declarations(source, "operation-surface.ts").unwrap();
    assert!(declarations.contains("private constructor();"));
    assert!(declarations.contains("value(): T;"));
    assert!(!declarations.contains("InternalOperationConfiguration"));
    assert!(!declarations.contains("InternalAttemptExecutor"));
    parse_ts_module_for_test(&declarations).unwrap();
    typecheck_declarations_if_available(&declarations);
}

#[cfg(unix)]
#[test]
fn wrapper_overrides_hostile_inherited_bump_intent() {
    let root = workspace_root();
    let directory = tempfile::tempdir().unwrap();
    let fake_bin = directory.path().join("bin");
    fs::create_dir(&fake_bin).unwrap();
    let fake_cargo = fake_bin.join("cargo");
    fs::write(
        &fake_cargo,
        "#!/bin/sh\nprintf '%s|%s|%s|%s\\n' \"${SYMBOL_GENERATION_MODE-unset}\" \"${SYMBOL_API_BUMP-unset}\" \"${SYMBOL_API_BUMP_EXPECTED-unset}\" \"${SYMBOL_API_BUMP_TARGET-unset}\" > \"$CAPTURE\"\n",
    )
    .unwrap();
    fs::set_permissions(&fake_cargo, fs::Permissions::from_mode(0o755)).unwrap();
    let inherited_path = std::env::var_os("PATH").unwrap();

    let ledger = read_ledger(&root).unwrap();
    let token = format!(
        "{}:{}:{}",
        ledger.version, ledger.absolute_revision, ledger.source_hash
    );
    let cases = [
        ("update", "update|unset|unset|unset".to_string()),
        ("check", "readonly|unset|unset|unset".to_string()),
        (
            "bump-minor",
            format!("update|minor|{token}|{}", ledger.version.next_minor()),
        ),
        (
            "bump-major",
            format!("update|major|{token}|{}", ledger.version.next_major()),
        ),
    ];
    for (command, expected) in cases {
        let capture = directory.path().join(format!("{command}.txt"));
        let status = Command::new(root.join("api-version"))
            .arg(command)
            .env("SYMBOL_API_BUMP", "hostile-inherited-value")
            .env("CAPTURE", &capture)
            .env(
                "PATH",
                std::env::join_paths(
                    std::iter::once(fake_bin.clone()).chain(std::env::split_paths(&inherited_path)),
                )
                .unwrap(),
            )
            .status()
            .unwrap();
        assert!(status.success(), "{command}");
        assert_eq!(
            fs::read_to_string(capture).unwrap(),
            format!("{expected}\n"),
            "{command}"
        );
    }
}

#[test]
fn unsafe_commits_cannot_reach_javascript_or_python_artifacts() {
    let root = workspace_root();
    for commit in [
        "deadbeef\n// injected",
        "deadbeef\n# injected",
        "deadbeef\";globalThis.pwned=true;//",
        "unknown\nprint('pwned')",
    ] {
        assert!(
            BuildProvenance::from_injected(commit.to_string(), false).is_err(),
            "{commit:?}"
        );
    }

    let ledger = VersionLedger {
        version: ApiVersion::new(2, 3, 4),
        absolute_revision: 57,
        source_hash: canonical_source_hash(&root).unwrap(),
    };
    for commit in ["deadbeef\n// injected", "deadbeef\n# injected"] {
        let metadata = GenerationMetadata {
            ledger: ledger.clone(),
            provenance: BuildProvenance {
                commit: commit.to_string(),
                dirty: false,
            },
        };
        assert!(generate_artifacts(&root, &metadata).is_err(), "{commit:?}");
    }

    let metadata = GenerationMetadata {
        ledger: VersionLedger {
            version: ApiVersion::new(2, 3, 4),
            absolute_revision: 57,
            source_hash: canonical_source_hash(&root).unwrap(),
        },
        provenance: BuildProvenance::from_injected("unknown".to_string(), false).unwrap(),
    };
    let artifacts = generate_artifacts(&root, &metadata).unwrap();
    assert!(artifacts.api_js.contains("\\\"commit\\\":\\\"unknown\\\""));
    assert!(artifacts.api_py.contains("\"commit\":\"unknown\""));
}

#[test]
fn nix_generated_sources_is_an_independent_read_only_derivation() {
    let root = workspace_root();
    let flake = std::fs::read_to_string(root.join("flake.nix")).unwrap();
    assert!(flake.contains("generatedSources = rustPlatform.buildRustPackage"));
    assert!(flake.contains("generated-sources = generatedSources;"));
    assert!(!flake.contains("generated-sources = package;"));
    assert!(flake.contains("lib.removeSuffix \"-dirty\" self.dirtyRev"));
    assert!(flake.contains("SYMBOL_BUILD_COMMIT = provenanceCommit;"));
    assert!(flake.contains("SYMBOL_BUILD_DIRTY = provenanceDirty;"));
    assert!(flake.contains("generated-provenance = provenance;"));

    let nix_check = std::fs::read_to_string(root.join("nix/check.sh")).unwrap();
    assert!(nix_check.contains("git -C \"$root\" rev-parse HEAD"));
    assert!(nix_check.contains("SYMBOL_NIX_BUILD_DIRTY=true"));
    assert!(nix_check.contains("nix flake check --impure"));
    let release = std::fs::read_to_string(root.join("release-check")).unwrap();
    assert!(release.contains("sh nix/check.sh"));
    assert!(!release.contains("nix build path:."));
}

fn workspace_root() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .unwrap()
}

fn test_metadata(root: &Path) -> GenerationMetadata {
    GenerationMetadata {
        ledger: VersionLedger {
            version: ApiVersion::new(2, 3, 4),
            absolute_revision: 57,
            source_hash: canonical_source_hash(root).unwrap(),
        },
        provenance: BuildProvenance::from_injected("0123456789abcdef".to_string(), true).unwrap(),
    }
}

fn runtime_exports(module: &Module) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    for item in &module.body {
        let ModuleItem::ModuleDecl(ModuleDecl::ExportDecl(export)) = item else {
            continue;
        };
        match &export.decl {
            Decl::Var(variable) => {
                for declarator in &variable.decls {
                    let Pat::Ident(identifier) = &declarator.name else {
                        continue;
                    };
                    names.insert(identifier.id.sym.to_string());
                }
            }
            Decl::Fn(function) => {
                names.insert(function.ident.sym.to_string());
            }
            Decl::Class(class) => {
                names.insert(class.ident.sym.to_string());
            }
            Decl::TsEnum(enumeration) => {
                names.insert(enumeration.id.sym.to_string());
            }
            Decl::TsInterface(_) | Decl::TsTypeAlias(_) | Decl::TsModule(_) | Decl::Using(_) => {}
        }
    }
    names
}

fn header_identity(source: &str) -> HeaderIdentity {
    HeaderIdentity {
        api_version: header_field(source, "API"),
        absolute_revision: header_field(source, "Absolute revision"),
        source_hash: header_field(source, "Source Blake3"),
        generator_version: header_field(source, "Generator version"),
        commit: header_field(source, "Commit"),
        state: header_field(source, "State"),
    }
}

fn header_field(source: &str, field: &str) -> String {
    source
        .lines()
        .map(|line| line.trim_start_matches('/').trim_start_matches('#').trim())
        .find_map(|line| line.strip_prefix(&format!("{field}: ")))
        .unwrap_or_else(|| panic!("missing generated header field {field}"))
        .to_string()
}

fn typecheck_declarations_if_available(declarations: &str) {
    let Ok(version) = Command::new("tsc").arg("--version").output() else {
        return;
    };
    assert!(version.status.success());
    let directory = tempfile::tempdir().unwrap();
    let declaration_path = directory.path().join("symbol.d.ts");
    fs::write(&declaration_path, declarations).unwrap();
    let output = Command::new("tsc")
        .args(["--noEmit", "--strict", "--skipLibCheck", "false"])
        .arg(&declaration_path)
        .current_dir(directory.path())
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
}
